#!/bin/bash

# Script run every 2 seconds
# Script shows:
#
#   [1] Queue name
#   [2] Number of processing messages
#   [3] Number of messages ready for processing
#   [4] Total number of messages
#   [5] Durability of queue
#   [6] The queue is temporary or not
#   [7] Number of consumers

watch 'sudo /usr/sbin/rabbitmqctl list_queues name messages_unacknowledged messages_ready messages durable auto_delete consumers | grep -v "\.\.\." | sort | column -t;'